### ISSUE TITLE
Publish on pypi?

### ISSUE THREAD

**Issue by paparent** [runekaagaard/django-crispy-forms-fancy-formsets#1]
Hi! I just found your project. Just want I wanted! It works well, after a few tweaks/bugs. Here's some question:

Is this the latest version or you have some local branch with bugs fixed (import UniFormNode from forms.py that isn't need (and doesn't exits on crispy-forms), and had a bug with helper...

Is the package will be publish on pypi for easier deployment?

I'm interrested in contributing to the project :)

PA

**Comment by runekaagaard** [comment]
Hey back

Thats super nice to hear! This is the latest version of the code, the bug you found must be because I didn't test the test project. Yes it should be on pypi. Added you as a contributor. Go crazy :)

**Comment by paparent** [comment]
Hi :)

I'll start contributing.. For now, I'll submit some pull request. There is no license yet in the project :( Do you feel confortable to use the same as in crispy-forms (MIT) ?

Thanks

**Comment by runekaagaard** [comment]
Hi

MIT is a fine license. If it matters to you, please add it. If we
could avoid big headers in every file, that would be great.

Thanks for your pull request, will look at it soon. There is some
feedback from the crispy-forms author on the generality of
fancy-formsets here:
https://github.com/maraujop/django-crispy-forms/issues/26. Interesting
stuff. I've been having a hard
time making fancy-formsets more flexible and generic. It's very much a
one-trick-pony. But maybe that's not bad?

Cheers
Rune

On Sun, Jul 1, 2012 at 7:05 PM, PA Parent
reply@reply.github.com
wrote:

**Comment by paparent** [comment]
Hi,

Thanks ! My next step: Add MIT license (cause it's not good to have not!), and publish to pypi. I'll add setup.py, MANIFEST.in etc.. Maybe we should start with version 0.1, and start from there. 

I'll do that hopefully today because I need it to go forward with my project :)

Thanks!

PA

**Comment by paparent** [comment]
And don't worry about changing all file! I'll add a LICENSE file, that's it! :)

**Comment by paparent** [comment]
Nice! It's now on pypi, and got 37 downloads already :)

**Comment by runekaagaard** [comment]
37??? How is that possible?

```
watch "pip install -I django-crispy-forms-fancy-formsets"
```

:)
