### ISSUE TITLE
empty_form

### ISSUE THREAD

**Issue by ouhouhsami** [runekaagaard/django-crispy-forms-fancy-formsets#3]
Hello, 

Thanks for sharing this app. It is relevant for one of my current use case.

I have a question about the way you add form to a formset. I would have use "formset.empty_form" value to dynamically create and add form to a formset. The way (it seems to me) that you add form, by just removing a hidden class prevent the app from being used with form having required values, because they will not validate, no ?

Regards,

**Comment by runekaagaard** [comment]
Hi

It works fine for required fields. Cheers!

**Comment by ouhouhsami** [comment]
Don't know what happen with my code, so I made changes here https://github.com/ouhouhsami/django-crispy-forms-fancy-formsets/commit/ee3579fce1aa230b621205a48adcaa6ba362cd67
